name: base
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.0.15
  dotted_border: ^2.1.0
  carousel_slider: ^4.0.0
  image_picker: ^1.1.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Router
  auto_route: ^7.8.4

  # Handle exception
  fpdart: ^1.1.0

  # Networking
  retrofit: ^4.0.3
  dio: ^5.4.0
  awesome_dio_interceptor: ^1.0.0

  # Firebase
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  firebase_auth: ^4.0.0

  #Icon
  icons_plus:
    ^4.0.0

  # Animation
  lottie: ^2.7.0
  flag: ^7.0.0
  font_awesome_flutter: ^10.6.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Order
  photo_view: ^0.14.0
  intl: ^0.18.1

# config launcher icon
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/movemate_logo.png"
#   min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: ^8.0.4
  riverpod_generator: ^2.3.6
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  plugin_platform_interface: ^2.1.7
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/

  # fonts:
  #   - family: Open Sans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/OpenSans-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/OpenSans-Bold.ttf
  #         weight: 700
